[project]
name = "metal-blobs"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asynckivy>=0.9.3",
    "kivy[base]>=2.3.1",
    "materialyoucolor>=2.0.10",
]
